<?php

namespace ContainerRxc1JTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LoO76W4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.loO76W4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.loO76W4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'championRepository' => ['privates', 'App\\Repository\\ChampionRepository', 'getChampionRepositoryService', true],
        ], [
            'championRepository' => 'App\\Repository\\ChampionRepository',
        ]);
    }
}
