<?php

namespace ContainerRxc1JTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WxVqZ5TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WxVqZ5T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WxVqZ5T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'champion' => ['privates', '.errored..service_locator.WxVqZ5T.App\\Entity\\Champion', NULL, 'Cannot autowire service ".service_locator.WxVqZ5T": it references class "App\\Entity\\Champion" but no such service exists.'],
        ], [
            'champion' => 'App\\Entity\\Champion',
        ]);
    }
}
