<?php

namespace ContainerRxc1JTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YoIZHffService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yoIZHff' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yoIZHff'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CreateChampionController::delete' => ['privates', '.service_locator.WxVqZ5T', 'get_ServiceLocator_WxVqZ5TService', true],
            'App\\Controller\\CreateChampionController::edit' => ['privates', '.service_locator.WxVqZ5T', 'get_ServiceLocator_WxVqZ5TService', true],
            'App\\Controller\\CreateChampionController::index' => ['privates', '.service_locator.loO76W4', 'get_ServiceLocator_LoO76W4Service', true],
            'App\\Controller\\CreateChampionController::show' => ['privates', '.service_locator.WxVqZ5T', 'get_ServiceLocator_WxVqZ5TService', true],
            'App\\Controller\\ListeDesChampionsController::index' => ['privates', '.service_locator.nlfXfZR', 'get_ServiceLocator_NlfXfZRService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CreateChampionController:delete' => ['privates', '.service_locator.WxVqZ5T', 'get_ServiceLocator_WxVqZ5TService', true],
            'App\\Controller\\CreateChampionController:edit' => ['privates', '.service_locator.WxVqZ5T', 'get_ServiceLocator_WxVqZ5TService', true],
            'App\\Controller\\CreateChampionController:index' => ['privates', '.service_locator.loO76W4', 'get_ServiceLocator_LoO76W4Service', true],
            'App\\Controller\\CreateChampionController:show' => ['privates', '.service_locator.WxVqZ5T', 'get_ServiceLocator_WxVqZ5TService', true],
            'App\\Controller\\ListeDesChampionsController:index' => ['privates', '.service_locator.nlfXfZR', 'get_ServiceLocator_NlfXfZRService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CreateChampionController::delete' => '?',
            'App\\Controller\\CreateChampionController::edit' => '?',
            'App\\Controller\\CreateChampionController::index' => '?',
            'App\\Controller\\CreateChampionController::show' => '?',
            'App\\Controller\\ListeDesChampionsController::index' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CreateChampionController:delete' => '?',
            'App\\Controller\\CreateChampionController:edit' => '?',
            'App\\Controller\\CreateChampionController:index' => '?',
            'App\\Controller\\CreateChampionController:show' => '?',
            'App\\Controller\\ListeDesChampionsController:index' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
