<?php

namespace ContainerRxc1JTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChampionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ChampionType' shared autowired service.
     *
     * @return \App\Form\ChampionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ChampionType.php';

        return $container->privates['App\\Form\\ChampionType'] = new \App\Form\ChampionType();
    }
}
