<?php

namespace ContainerRxc1JTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChampionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WxVqZ5T.App\Entity\Champion' shared service.
     *
     * @return \App\Entity\Champion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WxVqZ5T": it references class "App\\Entity\\Champion" but no such service exists.');
    }
}
