<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxc1JTf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxc1JTf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxc1JTf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxc1JTf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxc1JTf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rxc1JTf',
    'container.build_id' => 'b2c9d2c3',
    'container.build_time' => 1636712965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxc1JTf');
